"""Contracts and configuration for the anomaly representation model."""

from representation.layers.normalization import ConditionalBatchNorm
from representation.config import V1Config
from representation.contracts import (
    RepresentationBatch,
    RepresentationOutput,
    validate_batch,
    validate_output,
)
from representation.model import V1RepresentationModel
from representation.checkpoint import CheckpointManager, load_checkpoint, save_checkpoint
from representation.criterion import (
    FileContrastiveCriterion,
    JointRepresentationCriterion,
    LatentPredictionCriterion,
    ProgressiveLambda,
)
from representation.v2_config import FALLBACK_ORDER, V2Config, assert_encoder_inputs_clean
from representation.v2_contracts import (
    CONTEXT_ENERGY_FIELD,
    MONITORING_ENERGY_FIELD,
    POPULATION_ENERGY_FIELD,
    V2AnomalyConfidence,
    V2ContextPatchOutput,
    V2FailureRisk,
    V2FileState,
    V2PopulationPatchOutput,
    V2TrajectoryFeatures,
    validate_confidence,
    validate_context_patch_output,
    validate_file_state,
    validate_population_patch_output,
    validate_risk,
    validate_trajectory,
)
from representation.v2_patch import ContextConditionedPatchEncoder, PatchDistributionHead
from representation.v2_geometry import FrozenReference, GroupStats, HierarchicalMahalanobisGeometry
from representation.v2_objectives import (
    CounterfactualCriterion,
    covariance_loss,
    synthesize_corrupted_patches,
    variance_loss,
)
from representation.v2_aggregation import (
    DEFAULT_QUANTILE_LEVELS,
    DEV_VAL_COHORT_PREFIX,
    aggregate_file_state,
    calibrate_elevated_threshold,
    calibrate_elevated_threshold_with_provenance,
)
from representation.v2_trajectory import TrajectoryTracker
from representation.v2_risk import (
    CensoredSurvivalRisk,
    HealthyTailCalibrator,
    expected_feature_width,
    trajectory_feature_matrix,
)
from representation.v2_checkpoint import load_v2_checkpoint, save_v2_checkpoint
from representation.v2_trainer import V2Trainer, build_v2_training_stack
from representation.v2_inference import V2InferencePipeline, patch_regime_ids
from representation.v2_staged import (
    CONTROL_VARIANT,
    HYBRID_VARIANT,
    STAGE_EPOCHS,
    StageSpec,
    balance_matrix,
    control_coefficients,
    hybrid_coefficients,
    load_stage_config,
    resolve_commit,
    run_stage_cell,
    run_staged_config,
    stage_epochs,
)
from representation.inference import NormalReferenceBank, ReferenceBank, RepresentationInference, mad_threshold, prepare_reference_bank
from representation.geometry import (
    BatchConfig,
    BoundedEmbeddingExtractor,
    CompatibilityConfig,
    DiagnosticConfig,
    DiagnosticResult,
    EmbeddingExtractor,
    GeometryCompatibilityError,
    GeometryManifest,
    GeometryOutputPaths,
    GeometryRecord,
    NeighborConfig,
    ProjectionConfig,
    SamplingConfig,
    extract_embeddings,
)

__all__ = [
    "ConditionalBatchNorm",
    "V1Config",
    "V1RepresentationModel",
    "RepresentationBatch",
    "FileContrastiveCriterion",
    "JointRepresentationCriterion",
    "LatentPredictionCriterion",
    "ProgressiveLambda",
    "NormalReferenceBank",
    "ReferenceBank",
    "RepresentationInference",
    "mad_threshold",
    "prepare_reference_bank",
    "validate_batch",
    "CheckpointManager",
    "load_checkpoint",
    "save_checkpoint",
    "validate_output",
    "BatchConfig",
    "BoundedEmbeddingExtractor",
    "CompatibilityConfig",
    "DiagnosticConfig",
    "DiagnosticResult",
    "EmbeddingExtractor",
    "GeometryCompatibilityError",
    "GeometryManifest",
    "GeometryOutputPaths",
    "GeometryRecord",
    "NeighborConfig",
    "ProjectionConfig",
    "SamplingConfig",
    "extract_embeddings",
    "FALLBACK_ORDER",
    "V2Config",
    "assert_encoder_inputs_clean",
    "V2AnomalyConfidence",
    "V2ContextPatchOutput",
    "V2FailureRisk",
    "V2FileState",
    "V2PopulationPatchOutput",
    "V2TrajectoryFeatures",
    "CONTEXT_ENERGY_FIELD",
    "MONITORING_ENERGY_FIELD",
    "POPULATION_ENERGY_FIELD",
    "validate_confidence",
    "validate_context_patch_output",
    "validate_file_state",
    "validate_population_patch_output",
    "validate_risk",
    "validate_trajectory",
    "ContextConditionedPatchEncoder",
    "PatchDistributionHead",
    "FrozenReference",
    "GroupStats",
    "HierarchicalMahalanobisGeometry",
    "CounterfactualCriterion",
    "covariance_loss",
    "synthesize_corrupted_patches",
    "variance_loss",
    "DEFAULT_QUANTILE_LEVELS",
    "DEV_VAL_COHORT_PREFIX",
    "aggregate_file_state",
    "calibrate_elevated_threshold",
    "calibrate_elevated_threshold_with_provenance",
    "TrajectoryTracker",
    "CensoredSurvivalRisk",
    "HealthyTailCalibrator",
    "expected_feature_width",
    "trajectory_feature_matrix",
    "load_v2_checkpoint",
    "save_v2_checkpoint",
    "V2Trainer",
    "build_v2_training_stack",
    "V2InferencePipeline",
    "patch_regime_ids",
    "CONTROL_VARIANT",
    "HYBRID_VARIANT",
    "STAGE_EPOCHS",
    "StageSpec",
    "balance_matrix",
    "control_coefficients",
    "hybrid_coefficients",
    "load_stage_config",
    "resolve_commit",
    "run_stage_cell",
    "run_staged_config",
    "stage_epochs",
]
